import { findContentById } from '@src/core/utils/finder'
import _ from 'lodash'
import { baseStatsObject, StatsObject } from '../../baseConstant'
import { Stats } from '@src/domain/genshin/constant'

const Albedo = (c: number, a: number) => {
  const maxFatalReckoning = 4

  const content = [
    {
      type: 'toggle',
      id: 'calciteMight',
      text: `Calcite Might`,
      title: 'A1: Calcite Might',
      content: `Transient Blossoms generated by Abiogenesis: Solar Isotoma deal <span class="text-yellow">25%</span> more DMG to opponents whose HP is below <span class="text-yellow">50%</span>.`,
      show: a >= 1,
      default: true,
    },
    {
      type: 'number',
      id: 'fatalReckoningStacks',
      text: `Fatal Reckoning Stacks`,
      title: 'C2: Flower of Eden',
      content: `Transient Blossoms generated by Abiogenesis: Solar Isotoma grant Albedo Fatal Reckoning for <span class="text-yellow">30</span>s:
      <br />- Unleashing Rite of Progeniture: Tectonic Tide consumes all stacks of Fatal Reckoning. Each stack of Fatal Reckoning consumed increases the DMG dealt by Fatal Blossoms and Rite of Progeniture: Tectonic Tide's burst DMG by <span class="text-yellow">30%</span> of Albedo's DEF.
      <br />- This effect stacks up to <span class="text-yellow">4</span> times.`,
      show: c >= 2,
      min: 0,
      max: maxFatalReckoning,
      default: maxFatalReckoning,
    },
    {
      type: 'toggle',
      id: 'dustOfPurification',
      text: `Dust of Purification`,
      title: 'C6: Dust of Purification',
      content: `Active party members within the Solar Isotoma field who are protected by a shield created by Crystallize have their DMG increased by <span class="text-yellow">17%</span>.`,
      show: c >= 6,
      default: true,
    },
  ]

  const teammateContent = [
    {
      type: 'toggle',
      id: 'homuncularNature',
      text: `Homuncular Nature`,
      title: 'A4: Calcite Might',
      content: `Using Rite of Progeniture: Tectonic Tide increases the Elemental Mastery of nearby party members by <span class="text-yellow">125</span> for <span class="text-yellow">10</span>s.`,
      show: a >= 4,
      default: true,
    },
    {
      type: 'toggle',
      id: 'descentOfDivinity',
      text: `Descent of Divinity`,
      title: 'C4: Descent of Divinity',
      content: `Active party members within the Solar Isotoma field have their Plunging Attack DMG increased by <span class="text-yellow">30%</span>.`,
      show: c >= 4,
      default: true,
    },
    findContentById(content, 'dustOfPurification'),
  ]

  return {
    content,
    teammateContent,
    preCompute: (form: Record<string, any>) => {
      const base = _.cloneDeep(baseStatsObject)

      base.BURST_DMG += 0.3 * form.fatalReckoningStacks
    },
    preComputeShared: (base: StatsObject, form: Record<string, any>) => {
      base[Stats.ALL_DMG] += 0.17 * form.dustOfPurification
    },
  }
}

export default Albedo
