import { findContentById } from '@src/core/utils/finder'
import _ from 'lodash'
import { baseStatsObject, getPlungeScaling, StatsObject } from '../../baseConstant'
import { Element, ITalentLevel, Stats, TalentProperty } from '@src/domain/constant'

import { toPercentage } from '@src/core/utils/converter'
import { IContent, ITalent } from '@src/domain/conditional'
import { calcScaling } from '../../../../../core/utils/data_format'

const Albedo = (c: number, a: number, t: ITalentLevel) => {
  const upgrade = {
    normal: false,
    skill: c >= 3,
    burst: c >= 5,
  }
  const normal = t.normal + (upgrade.normal ? 3 : 0)
  const skill = t.skill + (upgrade.skill ? 3 : 0)
  const burst = t.burst + (upgrade.burst ? 3 : 0)

  const maxFatalReckoning = 4

  const talents: ITalent = {
    normal: {
      trace: `Normal Attack`,
      title: 'Favonius Bladework - Weiss',
      content: `<b>Normal Attack</b>
      <br />Performs up to 5 rapid strikes.
      <br />
      <br /><b>Charged Attack</b>
      <br />Consumes a certain amount of Stamina to unleash 2 rapid sword strikes.
      <br />
      <br /><b>Plunging Attack</b>
      <br />Plunges from mid-air to strike the ground below, damaging opponents along the path and dealing AoE DMG upon impact.
      `,
      image: 'Skill_A_01',
    },
    skill: {
      trace: `Elemental Skill`,
      title: 'Abiogenesis: Solar Isotoma',
      content: `Albedo creates a <b class="text-genshin-geo">Solar Isotoma</b> using alchemy, which deals <b class="text-genshin-geo">AoE Geo DMG</b> on appearance.
      <br />
      <br /><b class="text-genshin-geo">Solar Isotoma</b>
      <br />has the following properties:
      <br />- When opponents within the <b class="text-genshin-geo">Solar Isotoma</b> field take DMG, the <b class="text-genshin-geo">Solar Isotoma</b> will generate <b class="text-genshin-geo">Transient Blossoms</b> which deal <b class="text-genshin-geo">AoE Geo DMG</b>. DMG dealt scales off Albedo's DEF.
      <br />- <b class="text-genshin-geo">Transient Blossoms</b> can only be generated once every <span class="text-desc">2</span>s.
      <br />- When a character is located at the locus of the <b class="text-genshin-geo">Solar Isotoma</b>, the Solar Isotoma will accumulate Geo power to form a crystallized platform that lifts the character up to a certain height. Only one crystallized platform can exist at a time.
      <br />- <b class="text-genshin-geo">Solar Isotoma</b> is considered a <b class="text-genshin-geo">Geo construct</b>. Only one <b class="text-genshin-geo">Solar Isotoma</b> created by Albedo himself can exist at a time.
      <br />
      <br /><b>Hold</b> to designate the location of the skill.`,
      image: 'Skill_S_Albedo_01',
    },
    burst: {
      trace: `Elemental Burst`,
      title: 'Rite of Progeniture: Tectonic Tide',
      content: `Under Albedo's command, Geo crystals surge and burst forth, dealing <b class="text-genshin-geo">AoE Geo DMG</b> in front of him.
      <br />If a <b class="text-genshin-geo">Solar Isotoma</b> created by Albedo himself is on the field, <span class="text-desc">7</span> <b class="text-genshin-geo">Fatal Blossoms</b> will be generated in the <b class="text-genshin-geo">Solar Isotoma</b> field, bursting violently into bloom and dealing <b class="text-genshin-geo">AoE Geo DMG</b>.
      <br />
      <br /><b>Tectonic Tide</b> DMG and <b class="text-genshin-geo">Fatal Blossom</b> DMG will not generate <b class="text-genshin-geo">Transient Blossoms</b>.`,
      image: 'Skill_E_Albedo_01',
    },
    a1: {
      trace: `Ascension 1 Passive`,
      title: 'Calcite Might',
      content: `<b class="text-genshin-geo">Transient Blossoms</b> generated by <b>Abiogenesis: Solar Isotoma</b> deal <span class="text-desc">25%</span> more DMG to opponents whose HP is below <span class="text-desc">50%</span>.`,
      image: 'UI_Talent_S_Albedo_05',
    },
    a4: {
      trace: `Ascension 4 Passive`,
      title: 'Homuncular Nature',
      content: `Using <b>Rite of Progeniture: Tectonic Tide</b> increases the Elemental Mastery of nearby party members by <span class="text-desc">125</span> for <span class="text-desc">10</span>s.`,
      image: 'UI_Talent_S_Albedo_06',
    },
    util: {
      trace: `Utiliy Passive`,
      title: 'Flash of Genius',
      content: `When Albedo crafts Weapon Ascension Materials, he has a <span class="text-desc">10%</span> chance to receive double the product.`,
      image: 'UI_Talent_S_Alhatham_07',
    },
    c1: {
      trace: `Constellation 1`,
      title: 'Flower of Eden',
      content: `<b class="text-genshin-geo">Transient Blossoms</b> generated by <b>Abiogenesis: Solar Isotoma</b> deal <span class="text-desc">25%</span> more DMG to opponents whose HP is below <span class="text-desc">50%</span>.`,
      image: 'UI_Talent_S_Albedo_01',
    },
    c2: {
      trace: `Constellation 2`,
      title: 'Opening of Phanerozoic',
      content: `<b class="text-genshin-geo">Transient Blossoms</b> generated by <b>Abiogenesis: Solar Isotoma</b> grant Albedo <b>Fatal Reckoning</b> for <span class="text-desc">30</span>s:
      <br />- Unleashing <b>Rite of Progeniture: Tectonic Tide</b> consumes all stacks of <b>Fatal Reckoning</b>. Each stack of <b>Fatal Reckoning</b> consumed increases the DMG dealt by <b class="text-genshin-geo">Fatal Blossoms</b> and <b>Rite of Progeniture: Tectonic Tide</b>'s burst DMG by <span class="text-desc">30%</span> of Albedo's DEF.
      <br />- This effect stacks up to <span class="text-desc">4</span> times.`,
      image: 'UI_Talent_S_Albedo_02',
    },
    c3: {
      trace: `Constellation 3`,
      title: 'Grace of Helios',
      content: `Increases the Level of <b>Abiogenesis: Solar Isotoma</b> by <span class="text-desc">3</span>.
      <br />Maximum upgrade level is <span class="text-desc">15</span>.`,
      image: 'UI_Talent_U_Albedo_01',
    },
    c4: {
      trace: `Constellation 4`,
      title: 'Descent of Divinity',
      content: `Active party members within the <b class="text-genshin-geo">Solar Isotoma</b> field have their Plunging Attack DMG increased by <span class="text-desc">30%</span>.`,
      image: 'UI_Talent_S_Albedo_03',
    },
    c5: {
      trace: `Constellation 5`,
      title: 'Tide of Hadean',
      content: `Increases the Level of <b>Rite of Progeniture: Tectonic Tide</b> by <span class="text-desc">3</span>.
      <br />Maximum upgrade level is <span class="text-desc">15</span>.`,
      image: 'UI_Talent_U_Albedo_02',
    },
    c6: {
      trace: `Constellation 6`,
      title: 'Dust of Purification',
      content: `Active party members within the <b class="text-genshin-geo">Solar Isotoma</b> field who are protected by a shield created by Crystallize have their DMG increased by <span class="text-desc">17%</span>.`,
      image: 'UI_Talent_S_Albedo_04',
    },
  }

  const content: IContent[] = [
    {
      type: 'toggle',
      id: 'calciteMight',
      text: `Calcite Might`,
      ...talents.a1,
      show: a >= 1,
      default: true,
    },
    {
      type: 'toggle',
      id: 'homuncularNature',
      text: `A4 Team EM Buff`,
      ...talents.a4,
      show: a >= 4,
      default: true,
    },
    {
      type: 'number',
      id: 'fatalReckoningStacks',
      text: `Fatal Reckoning Stacks`,
      ...talents.c2,
      show: c >= 2,
      min: 0,
      max: maxFatalReckoning,
      default: maxFatalReckoning,
    },
    {
      type: 'toggle',
      id: 'descentOfDivinity',
      text: `C4 Plunge DMG Bonus`,
      ...talents.c4,
      show: c >= 4,
      default: false,
    },
    {
      type: 'toggle',
      id: 'dustOfPurification',
      text: `C6 Crystallize Shield Buff`,
      ...talents.c6,
      show: c >= 6,
      default: false,
    },
  ]

  const teammateContent: IContent[] = [findContentById(content, 'homuncularNature')]

  return {
    upgrade,
    talents,
    content,
    teammateContent,
    allyContent: [findContentById(content, 'descentOfDivinity'), findContentById(content, 'dustOfPurification')],
    preCompute: (x: StatsObject, form: Record<string, any>) => {
      const base = _.cloneDeep(x)

      const fatalReckoningScaling =
        form.fatalReckoningStacks > 0 ? [{ scaling: 0.3 * form.fatalReckoningStacks, multiplier: Stats.DEF }] : []

      base.BASIC_SCALING = [
        {
          name: '1-Hit',
          value: [{ scaling: calcScaling(0.3674, normal, 'physical', '1_alt'), multiplier: Stats.ATK }],
          element: Element.PHYSICAL,
          property: TalentProperty.NA,
        },
        {
          name: '2-Hit',
          value: [{ scaling: calcScaling(0.3674, normal, 'physical', '1_alt'), multiplier: Stats.ATK }],
          element: Element.PHYSICAL,
          property: TalentProperty.NA,
        },
        {
          name: '3-Hit',
          value: [{ scaling: calcScaling(0.4745, normal, 'physical', '1_alt'), multiplier: Stats.ATK }],
          element: Element.PHYSICAL,
          property: TalentProperty.NA,
        },
        {
          name: '4-Hit',
          value: [{ scaling: calcScaling(0.4975, normal, 'physical', '1_alt'), multiplier: Stats.ATK }],
          element: Element.PHYSICAL,
          property: TalentProperty.NA,
        },
        {
          name: '5-Hit',
          value: [{ scaling: calcScaling(0.6207, normal, 'physical', '1_alt'), multiplier: Stats.ATK }],
          element: Element.PHYSICAL,
          property: TalentProperty.NA,
        },
      ]
      base.CHARGE_SCALING = [
        {
          name: '1-Hit',
          value: [{ scaling: calcScaling(0.473, normal, 'physical', '1_alt'), multiplier: Stats.ATK }],
          element: Element.PHYSICAL,
          property: TalentProperty.CA,
        },
        {
          name: '2-Hit',
          value: [{ scaling: calcScaling(0.602, normal, 'physical', '1_alt'), multiplier: Stats.ATK }],
          element: Element.PHYSICAL,
          property: TalentProperty.CA,
        },
      ]
      base.PLUNGE_SCALING = getPlungeScaling('base', normal)
      base.SKILL_SCALING = [
        {
          name: 'Skill DMG',
          value: [{ scaling: calcScaling(1.304, skill, 'elemental', '1'), multiplier: Stats.ATK }],
          element: Element.GEO,
          property: TalentProperty.SKILL,
        },
        {
          name: 'Transient Blossom DMG',
          value: [{ scaling: calcScaling(1.336, skill, 'elemental', '1'), multiplier: Stats.DEF }],
          element: Element.GEO,
          property: TalentProperty.SKILL,
          bonus: form.calciteMight ? 0.25 : 0,
        },
      ]
      base.BURST_SCALING = [
        {
          name: 'Skill DMG',
          value: [
            { scaling: calcScaling(3.672, burst, 'elemental', '1'), multiplier: Stats.ATK },
            ...fatalReckoningScaling,
          ],
          element: Element.GEO,
          property: TalentProperty.BURST,
        },
        {
          name: 'Fatal Blossom DMG [x7]',
          value: [
            { scaling: calcScaling(0.72, burst, 'elemental', '1'), multiplier: Stats.DEF },
            ...fatalReckoningScaling,
          ],
          element: Element.GEO,
          property: TalentProperty.BURST,
        },
      ]

      if (form.dustOfPurification) base[Stats.ALL_DMG].push({ value: 0.17, name: 'Constellation 6', source: `Self` })
      if (form.homuncularNature) base[Stats.EM].push({ value: 125, name: 'Ascension 4 Passive', source: `Self` })
      if (form.descentOfDivinity) base.PLUNGE_DMG.push({ value: 0.3, name: 'Constellation 4', source: `Self` })

      return base
    },
    preComputeShared: (own: StatsObject, base: StatsObject, form: Record<string, any>, aForm: Record<string, any>) => {
      if (aForm.dustOfPurification) base[Stats.ALL_DMG].push({ value: 0.17, name: 'Constellation 6', source: `Albedo` })
      if (form.homuncularNature) base[Stats.EM].push({ value: 250, name: 'Ascension 4 Passive', source: `Albedo` })
      if (aForm.descentOfDivinity) base.PLUNGE_DMG.push({ value: 0.3, name: 'Constellation 4', source: `Albedo` })

      return base
    },
    postCompute: (base: StatsObject, form: Record<string, any>) => {
      return base
    },
  }
}

export default Albedo
