import { findContentById } from '@src/core/utils/finder'
import _ from 'lodash'
import { baseStatsObject, getPlungeScaling, StatsObject } from '../../baseConstant'
import { Element, Stats, TalentProperty } from '@src/domain/genshin/constant'
import { StatObjectT } from '@src/core/hooks/useStat'
import { toPercentage } from '@src/core/utils/converter'

const Albedo = (c: number, a: number, stat: StatObjectT) => {
  const maxFatalReckoning = 4

  const content = [
    {
      type: 'toggle',
      id: 'calciteMight',
      text: `Calcite Might`,
      title: 'A1: Calcite Might',
      content: `Transient Blossoms generated by Abiogenesis: Solar Isotoma deal <span class="text-yellow">25%</span> more DMG to opponents whose HP is below <span class="text-yellow">50%</span>.`,
      show: a >= 1,
      value: [{ name: 'Transient Blossoms DMG', value: 0.25, formatter: toPercentage }],
      default: true,
    },
    {
      type: 'toggle',
      id: 'homuncularNature',
      text: `Homuncular Nature`,
      title: 'A4: Homuncular Nature',
      content: `Using Rite of Progeniture: Tectonic Tide increases the Elemental Mastery of nearby party members by <span class="text-yellow">125</span> for <span class="text-yellow">10</span>s.`,
      show: a >= 4,
      value: [{ name: Stats.EM, value: 125, formatter: _.toString }],
      default: true,
    },
    {
      type: 'number',
      id: 'fatalReckoningStacks',
      text: `Fatal Reckoning Stacks`,
      title: 'C2: Flower of Eden',
      content: `Transient Blossoms generated by Abiogenesis: Solar Isotoma grant Albedo Fatal Reckoning for <span class="text-yellow">30</span>s:
      <br />- Unleashing Rite of Progeniture: Tectonic Tide consumes all stacks of Fatal Reckoning. Each stack of Fatal Reckoning consumed increases the DMG dealt by Fatal Blossoms and Rite of Progeniture: Tectonic Tide's burst DMG by <span class="text-yellow">30%</span> of Albedo's DEF.
      <br />- This effect stacks up to <span class="text-yellow">4</span> times.`,
      show: c >= 2,
      value: [{ name: 'Elemental Burst DMG', value: 0.3 * stat.def, formatter: _.floor }],
      min: 0,
      max: maxFatalReckoning,
      default: maxFatalReckoning,
    },
    {
      type: 'toggle',
      id: 'descentOfDivinity',
      text: `Descent of Divinity`,
      title: 'C4: Descent of Divinity',
      content: `Active party members within the Solar Isotoma field have their Plunging Attack DMG increased by <span class="text-yellow">30%</span>.`,
      show: c >= 4,
      value: [{ name: 'Plunge DMG%', value: 0.3, formatter: toPercentage }],
      default: true,
    },
    {
      type: 'toggle',
      id: 'dustOfPurification',
      text: `Dust of Purification`,
      title: 'C6: Dust of Purification',
      content: `Active party members within the Solar Isotoma field who are protected by a shield created by Crystallize have their DMG increased by <span class="text-yellow">17%</span>.`,
      show: c >= 6,
      value: [{ name: Stats.ALL_DMG, value: 0.17, formatter: toPercentage }],
      default: true,
    },
  ]

  const teammateContent = [
    findContentById(content, 'homuncularNature'),
    findContentById(content, 'descentOfDivinity'),
    findContentById(content, 'dustOfPurification'),
  ]

  return {
    content,
    teammateContent,
    preCompute: (form: Record<string, any>) => {
      const base = _.cloneDeep(baseStatsObject)

      base.BASIC_SCALING = [
        { name: '1-Hit', value: 0.3674 * stat.atk, element: Element.PHYSICAL, property: TalentProperty.NA },
        { name: '2-Hit', value: 0.3674 * stat.atk, element: Element.PHYSICAL, property: TalentProperty.NA },
        { name: '3-Hit', value: 0.4745 * stat.atk, element: Element.PHYSICAL, property: TalentProperty.NA },
        { name: '4-Hit', value: 0.4975 * stat.atk, element: Element.PHYSICAL, property: TalentProperty.NA },
        { name: '5-Hit', value: 0.6207 * stat.atk, element: Element.PHYSICAL, property: TalentProperty.NA },
      ]
      base.CHARGE_SCALING = [
        { name: '1-Hit', value: 0.473 * stat.atk, element: Element.PHYSICAL, property: TalentProperty.CA },
        { name: '2-Hit', value: 0.602 * stat.atk, element: Element.PHYSICAL, property: TalentProperty.CA },
      ]
      base.PLUNGE_SCALING = getPlungeScaling('base', stat.atk)
      base.SKILL_SCALING = [
        { name: 'Skill DMG', value: 1.304 * stat.atk, element: Element.GEO, property: TalentProperty.SKILL },
        {
          name: 'Transient Blossom DMG',
          value: 1.336 * stat.def,
          element: Element.GEO,
          property: TalentProperty.SKILL,
        },
      ]
      base.BURST_SCALING = [
        { name: 'Skill DMG', value: 3.672 * stat.atk, element: Element.GEO, property: TalentProperty.BURST },
        {
          name: 'Fatal Blossom DMG',
          value: 0.72 * stat.def + (0.3 * stat.def * form.fatalReckoningStacks || 0),
          element: Element.GEO,
          property: TalentProperty.BURST,
        },
      ]

      base[Stats.ALL_DMG] += 0.17 * (form.dustOfPurification || 0)
      base[Stats.EM] += 250 * (form.homuncularNature || 0)
      base.PLUNGE_DMG += 0.3 * (form.descentOfDivinity || 0)

      return base
    },
    preComputeShared: (base: StatsObject, form: Record<string, any>) => {
      base[Stats.ALL_DMG] += 0.17 * (form.dustOfPurification || 0)
      base[Stats.EM] += 250 * (form.homuncularNature || 0)
      base.PLUNGE_DMG += 0.3 * (form.descentOfDivinity || 0)

      return base
    },
  }
}

export default Albedo
